@PortfolioRiskEngine.Api_HostAddress = http://localhost:5118

POST http://localhost:5118/riskengine/calculate-risk
Accept: application/json
Content-Type: application/json

{
  "countryPercentageChanges": {
    "GB": -5.12,
    "US": -4.34,
    "FR": -3.87,
    "DE": -1.23,
    "SG": -5.5,
    "GR": -5.68
  }
}



###

GET  http://localhost:5118/RunsSearch/search-runs?pageNumber=1&pageSize=20
Accept: application/json

###

